name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: CI Build
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'
    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: 11
        distribution: adopt
    - name: Build Xtext Example
      shell: bash
      run: |
        cd examples/states-xtext/language-server
        ./gradlew build
    - name: Build Packages
      shell: bash
      run: yarn
